_prefs: 
  mapid: lrqdo.2f512fdf
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -18.0773
  - 27.7691
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - elhierro-lines
  - elhierro-coasts
maxzoom: 18
minzoom: 0
name: elhierro-coasts
source: "mapbox:///lrqdo.7e9a6dea"
styles: 
  - style.mss
template: ''
